In [2]:
import pandas as pd

In [11]:
path = "C:/bigcon/"
var_df = pd.read_csv(path + "output\data\k_table.csv", encoding = 'cp949',index_col= 0)
var_df.head(5)

         기존충전소      세대수  주차가능수  주요건물수(영화관,대형점포)  ev_traffic        면적
adng_nm
구갈동        112  10839.0  546.0              4.0   16.838410  0.000423
구성동        145  12235.0  122.0              2.0    6.826027  0.000681
기흥동        218   6119.0   34.0              2.0    3.861742  0.001185
남사읍         77   6800.0  122.0              0.0    4.258176  0.005940
동백1동        69   9419.0    0.0              0.0    3.189948  0.000421

In [12]:
bpi = pd.read_csv(path +'input/additional_dataset/bpi.csv',index_col=0)
bpi = bpi.set_index(var_df.index)
var_df['bpi'] = bpi

In [13]:
var_df['포화도'] = var_df['bpi']/var_df['기존충전소']
var_df.head(5)

,기존충전소,세대수,주차가능수,"주요건물수(영화관,대형점포)",ev_traffic,면적,bpi,포화도
adng_nm,,,,,,,,
구갈동,112,10839.0,546.0,4.0,16.838410,0.000423,0.038676,0.000345
구성동,145,12235.0,122.0,2.0,6.826027,0.000681,0.035247,0.000243
기흥동,218,6119.0,34.0,2.0,3.861742,0.001185,0.023412,0.000107
남사읍,77,6800.0,122.0,0.0,4.258176,0.005940,0.025461,0.000331
동백1동,69,9419.0,0.0,0.0,3.189948,0.000421,0.010546,0.000153

In [14]:
var_df_refine = var_df.drop(['기존충전소','주요건물수(영화관,대형점포)'], axis=1)
var_df_refine['bpi'] = bpi
var_df_refine.head(5)

             세대수  주차가능수  ev_traffic        면적       bpi       포화도
adng_nm
구갈동      10839.0  546.0   16.838410  0.000423  0.038676  0.000345
구성동      12235.0  122.0    6.826027  0.000681  0.035247  0.000243
기흥동       6119.0   34.0    3.861742  0.001185  0.023412  0.000107
남사읍       6800.0  122.0    4.258176  0.005940  0.025461  0.000331
동백1동      9419.0    0.0    3.189948  0.000421  0.010546  0.000153

In [15]:
build2_df = pd.read_csv(path + "output\data\checkpoint\건물2.csv", encoding = 'utf-8',index_col=0)
build3_df = pd.read_csv(path + "output\data\checkpoint\건물3.csv", encoding = 'utf-8',index_col= 0)

In [16]:
build3_df

         x
adng_nm
구갈동      4
구성동      2
기흥동      2
남사읍      0
동백1동     0
동백2동     2
동백3동     1
동부동      0
동천동      0
마북동      0
모현읍      0
백암면      0
보라동      0
보정동      0
상갈동      0
상하동      0
상현1동     2
상현2동     0
서농동      0
성복동      2
신갈동      1
신봉동      0
양지면      0
역삼동      2
영덕1동     0
영덕2동     0
원삼면      0
유림동      0
이동읍      0
죽전1동     0
죽전2동     2
중앙동      3
포곡읍      0
풍덕천1동    0
풍덕천2동    0

In [17]:
var_df_refine['x_x'] , var_df_refine['x_y'] = build2_df , build3_df
var_df_refine

             세대수   주차가능수  ev_traffic        면적       bpi       포화도  x_x  x_y
adng_nm
구갈동      10839.0   546.0   16.838410  0.000423  0.038676  0.000345    1    4
구성동      12235.0   122.0    6.826027  0.000681  0.035247  0.000243    0    2
기흥동       6119.0    34.0    3.861742  0.001185  0.023412  0.000107    0    2
남사읍       6800.0   122.0    4.258176  0.005940  0.025461  0.000331    0    0
동백1동      9419.0     0.0    3.189948  0.000421  0.010546  0.000153    0    0
동백2동      6945.0   122.0    8.380843  0.000493  0.010523  0.000080    7    2
동백3동      7378.0     0.0    1.509640  0.000148  0.024015  0.000087    0    1
동부동       2132.0   518.0    2.436028  0.002450  0.029156  0.001080    0    0
동천동      13203.0    35.0   10.949134  0.001679  0.049761  0.000263    0    0
마북동       9505.0   210.0    3.969491  0.000534  0.039556  0.000259    1    0
모현읍       1500.0   165.0    9.176900  0.005119  0.014629  0.000266    1    0
백암면        228.0   131.0    1.321207  0.006676  0.032498  0.003250    0    0
보라동       9460.0     0.0    5.958875  0.001037  0.024685  0.000191    0    0
보정동       8522.0   230.0    8.862262  0.000689  0.016199  0.000112    0    0
상갈동       3567.0   259.0    1.059567  0.000199  0.036292  0.000931    1    0
상하동       7256.0    43.0    2.706822  0.000580  0.012043  0.000215    6    0
상현1동     14325.0    35.0    7.943636  0.000347  0.028239  0.000103    0    2
상현2동     10265.0   158.0    2.843734  0.000162  0.019429  0.000194    0    0
서농동       6838.0    31.0    3.585888  0.000568  0.026945  0.000303    2    0
성복동      16922.0    47.0    6.532488  0.000513  0.030755  0.000099    0    2
신갈동      11367.0   989.0    8.033562  0.000470  0.027671  0.000199    0    1
신봉동      12441.0    46.0    3.614244  0.000664  0.025010  0.000102    0    0
양지면        390.0    64.0    4.471293  0.005867  0.021765  0.001280    1    0
역삼동       9952.0  1526.0   11.365975  0.001247  0.017958  0.000150   13    2
영덕1동      8315.0    37.0    7.907438  0.000407  0.021517  0.000234    0    0
영덕2동      5155.0     0.0    2.459000  0.000475  0.028927  0.000281    0    0
원삼면          0.0   194.0    1.073829  0.006106  0.033732  0.001874    0    0
유림동       5757.0   193.0    6.262200  0.001359  0.035311  0.000447    9    0
이동읍       3235.0    60.0    6.090206  0.007725  0.032840  0.000764    3    0
죽전1동     16757.0    52.0   10.685426  0.000464  0.050187  0.000316    1    0
죽전2동      5592.0   483.0    1.928488  0.000121  0.018239  0.000388    0    2
중앙동       4380.0  1627.0    7.507683  0.000809  0.043385  0.000700   10    3
포곡읍       3399.0   192.0    9.413816  0.004242  0.041134  0.000596    0    0
풍덕천1동     9918.0  1046.0    8.623708  0.000166  0.027932  0.000621    0    0
풍덕천2동    12552.0   513.0    5.339203  0.000184  0.046326  0.000579    0    0

In [18]:
final_k_table = var_df_refine

In [19]:
final_k_table.to_csv(path + "output\data\k_table_final.csv")